# Generated by Django 4.1.7 on 2023-10-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('amazon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_link', models.URLField()),
                ('flipkart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flipkart_link', models.URLField()),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
